"""Kaset baseline — the whole schema, from empty.

This replaces the 30 SlateClub-era migrations, whose chain was broken: two
revisions both claimed 0014_chapters as their parent and were never merged, so
`alembic upgrade head` failed on any fresh database. That went unnoticed only
because main.py ran create_all on startup. It no longer does — this chain is
now the single source of schema truth.

Squashing was safe because the rebase discarded the old dev data by decision.
Everything after this point is a normal incremental migration.

Revision ID: 0001_kaset_baseline
Revises:
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_kaset_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_cache',
    sa.Column('seed_tmdb_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('seed_tmdb_id', 'month')
    )
    op.create_table('movies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tmdbId', sa.Integer(), nullable=False),
    sa.Column('mediaType', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('posterPath', sa.String(), nullable=True),
    sa.Column('backdropPath', sa.String(), nullable=True),
    sa.Column('releaseDate', sa.String(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('voteAverage', sa.Float(), nullable=True),
    sa.Column('voteCount', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('originalLanguage', sa.String(), nullable=True),
    sa.Column('genres', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('credits', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdbId', 'mediaType')
    )
    op.create_index(op.f('ix_movies_mediaType'), 'movies', ['mediaType'], unique=False)
    op.create_index(op.f('ix_movies_tmdbId'), 'movies', ['tmdbId'], unique=False)
    op.create_table('reddit_cache',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id', 'month')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('avatarUrl', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('googleId', sa.String(), nullable=True),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('googleId')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('movie_id', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_user_created', 'activity_events', ['user_id', 'created_at'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user1_id', sa.String(), nullable=False),
    sa.Column('user2_id', sa.String(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_preview', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id')
    )
    op.create_index(op.f('ix_chat_conversations_user1_id'), 'chat_conversations', ['user1_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user2_id'), 'chat_conversations', ['user2_id'], unique=False)
    op.create_table('currently_watching',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('movieId', sa.String(), nullable=False),
    sa.Column('progressPct', sa.Float(), nullable=False),
    sa.Column('startedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'movieId')
    )
    op.create_table('dnf_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('movieId', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('stoppedAt', sa.String(), nullable=True),
    sa.Column('progressPct', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'movieId')
    )
    op.create_table('favorite_movies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tmdb_id')
    )
    op.create_table('favorite_people',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_path', sa.String(), nullable=True),
    sa.Column('known_for', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tmdb_id')
    )
    op.create_table('film_dms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_dms_recipient_id'), 'film_dms', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_film_dms_sender_id'), 'film_dms', ['sender_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('follower_id', sa.String(), nullable=False),
    sa.Column('following_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id')
    )
    op.create_table('language_selections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('onboarding_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('poster_picks', sa.JSON(), nullable=True),
    sa.Column('mood_pacing', sa.Float(), nullable=True),
    sa.Column('mood_tone', sa.Float(), nullable=True),
    sa.Column('mood_realism', sa.Float(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('prefers_theatres', sa.Boolean(), nullable=True),
    sa.Column('origin_film_tmdb_id', sa.Integer(), nullable=True),
    sa.Column('welcomed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_signals_user_id'), 'onboarding_signals', ['user_id'], unique=True)
    op.create_table('ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('movieId', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'movieId')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('spoiler', sa.Boolean(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('notif_opt_out', sa.JSON(), nullable=True),
    sa.Column('profile_visibility', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('watch_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('movieId', sa.String(), nullable=False),
    sa.Column('completionPct', sa.Float(), nullable=False),
    sa.Column('watchedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'movieId')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('movieId', sa.String(), nullable=False),
    sa.Column('reasonType', sa.String(), nullable=True),
    sa.Column('reasonReference', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'movieId')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_table('watch_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('movieId', sa.String(), nullable=False),
    sa.Column('watchedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('isRewatch', sa.Boolean(), nullable=False),
    sa.Column('atTheatre', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('reviewId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewId'], ['reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlog_user_movie', 'watch_log', ['userId', 'movieId'], unique=False)
    op.create_index('ix_watchlog_user_watched', 'watch_log', ['userId', 'watchedAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchlog_user_watched', table_name='watch_log')
    op.drop_index('ix_watchlog_user_movie', table_name='watch_log')
    op.drop_table('watch_log')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('watchlist_items')
    op.drop_table('watch_history')
    op.drop_table('user_preferences')
    op.drop_table('reviews')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_onboarding_signals_user_id'), table_name='onboarding_signals')
    op.drop_table('onboarding_signals')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('language_selections')
    op.drop_table('follows')
    op.drop_index(op.f('ix_film_dms_sender_id'), table_name='film_dms')
    op.drop_index(op.f('ix_film_dms_recipient_id'), table_name='film_dms')
    op.drop_table('film_dms')
    op.drop_table('favorite_people')
    op.drop_table('favorite_movies')
    op.drop_table('dnf_entries')
    op.drop_table('currently_watching')
    op.drop_index(op.f('ix_chat_conversations_user2_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_user1_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index('ix_activity_user_created', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reddit_cache')
    op.drop_index(op.f('ix_movies_tmdbId'), table_name='movies')
    op.drop_index(op.f('ix_movies_mediaType'), table_name='movies')
    op.drop_table('movies')
    op.drop_table('discovery_cache')
    # ### end Alembic commands ###
