"""viewing preferences

Revision ID: 0002_viewing_preferences
Revises: 0001_kaset_baseline
Create Date: 2026-08-12 15:46:32.687928
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_viewing_preferences'
down_revision: Union[str, None] = '0001_kaset_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewing_preferences',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('prefers_theatre', sa.Boolean(), nullable=False),
    sa.Column('preferred_decades', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index('ix_onboarding_signals_user_id', table_name='onboarding_signals')
    op.drop_table('onboarding_signals')
    # server_default so this is safe against a table that already has rows —
    # without it the NOT NULL add fails on any populated favourites list.
    op.add_column(
        'favorite_movies',
        sa.Column('position', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'favorite_people',
        sa.Column('position', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_people', 'position')
    op.drop_column('favorite_movies', 'position')
    op.create_table('onboarding_signals',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('poster_picks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mood_pacing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mood_tone', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mood_realism', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('platforms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('prefers_theatres', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('origin_film_tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('welcomed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ready_shown_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='onboarding_signals_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='onboarding_signals_pkey')
    )
    op.create_index('ix_onboarding_signals_user_id', 'onboarding_signals', ['user_id'], unique=True)
    op.drop_table('viewing_preferences')
    # ### end Alembic commands ###
