"""films only

Revision ID: 0003_films_only
Revises: 0002_viewing_preferences
Create Date: 2026-08-13 12:01:35.966925
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003_films_only'
down_revision: Union[str, None] = '0002_viewing_preferences'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dnf_entries')
    op.drop_index('ix_movies_mediaType', table_name='movies')
    op.drop_constraint('movies_tmdbId_mediaType_key', 'movies', type_='unique')
    # Named explicitly: autogenerate emits None here, which downgrade cannot drop.
    op.create_unique_constraint('movies_tmdbId_key', 'movies', ['tmdbId'])
    op.drop_column('movies', 'mediaType')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('mediaType', sa.VARCHAR(), autoincrement=False, nullable=False, server_default='movie'))
    op.drop_constraint('movies_tmdbId_key', 'movies', type_='unique')
    op.create_unique_constraint('movies_tmdbId_mediaType_key', 'movies', ['tmdbId', 'mediaType'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_movies_mediaType', 'movies', ['mediaType'], unique=False)
    op.create_table('dnf_entries',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('movieId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stoppedAt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('progressPct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movies.id'], name='dnf_entries_movieId_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='dnf_entries_userId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dnf_entries_pkey'),
    sa.UniqueConstraint('userId', 'movieId', name='dnf_entries_userId_movieId_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
