"""discovery evidence

Revision ID: 0006_discovery_evidence
Revises: 0005_unified_messaging
Create Date: 2026-08-13 17:24:20.578189
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006_discovery_evidence'
down_revision: Union[str, None] = '0005_unified_messaging'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seed_tmdb_id', sa.Integer(), nullable=False),
    sa.Column('candidate_tmdb_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('mention_context', sa.Text(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('authority_weight', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_evidence_seed_tmdb_id'), 'discovery_evidence', ['seed_tmdb_id'], unique=False)
    op.create_index('ix_evidence_seed_candidate', 'discovery_evidence', ['seed_tmdb_id', 'candidate_tmdb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_seed_candidate', table_name='discovery_evidence')
    op.drop_index(op.f('ix_discovery_evidence_seed_tmdb_id'), table_name='discovery_evidence')
    op.drop_table('discovery_evidence')
    # ### end Alembic commands ###
