"""candidate metadata on evidence

Revision ID: 0007_evidence_candidate_meta
Revises: 0006_discovery_evidence
Create Date: 2026-08-13 17:36:00.167183
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0007_evidence_candidate_meta'
down_revision: Union[str, None] = '0006_discovery_evidence'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery_evidence', sa.Column('candidate_title', sa.String(), nullable=False, server_default=''))
    op.add_column('discovery_evidence', sa.Column('candidate_year', sa.String(), nullable=True))
    op.add_column('discovery_evidence', sa.Column('candidate_poster_path', sa.String(), nullable=True))
    op.add_column('discovery_evidence', sa.Column('candidate_popularity', sa.Float(), nullable=True))
    op.add_column('discovery_evidence', sa.Column('candidate_language', sa.String(), nullable=True))
    op.add_column('discovery_evidence', sa.Column('candidate_genres', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery_evidence', 'candidate_genres')
    op.drop_column('discovery_evidence', 'candidate_language')
    op.drop_column('discovery_evidence', 'candidate_popularity')
    op.drop_column('discovery_evidence', 'candidate_poster_path')
    op.drop_column('discovery_evidence', 'candidate_year')
    op.drop_column('discovery_evidence', 'candidate_title')
    # ### end Alembic commands ###
