"""watchlists and blends

Revision ID: 0008_watchlists_blends
Revises: 0007_evidence_candidate_meta
Create Date: 2026-08-13 23:17:27.118744
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0008_watchlists_blends'
down_revision: Union[str, None] = '0007_evidence_candidate_meta'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blends',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('invite_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blends_creator_id'), 'blends', ['creator_id'], unique=False)
    op.create_index(op.f('ix_blends_invite_token'), 'blends', ['invite_token'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('blend_members',
    sa.Column('blend_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blend_id'], ['blends.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blend_id', 'user_id')
    )
    op.create_table('watchlist_films',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'tmdb_id')
    )
    op.create_index('ix_watchlist_films_order', 'watchlist_films', ['watchlist_id', 'position'], unique=False)
    op.create_index(op.f('ix_watchlist_films_watchlist_id'), 'watchlist_films', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_films_watchlist_id'), table_name='watchlist_films')
    op.drop_index('ix_watchlist_films_order', table_name='watchlist_films')
    op.drop_table('watchlist_films')
    op.drop_table('blend_members')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_blends_invite_token'), table_name='blends')
    op.drop_index(op.f('ix_blends_creator_id'), table_name='blends')
    op.drop_table('blends')
    # ### end Alembic commands ###
